[package]
name = "alloy"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy = { version = "0.1.4", features = ["full"] }
eyre = "0.6.12"
tokio = { version = "1.38.0", features = ["full"] }
reqwest = "0.12.5"
dotenv = "0.15.0"
