[package]
name = "base"
version = "0.1.0"
edition = "2021"

[dependencies]
minijinja-embed = "2.1.1"
minijinja = "2.1.1"
rust-embed = "8.5.0"
mime_guess = "2.0.5"

[build-dependencies]
minijinja-embed = "2.1.1"
