[package]
name = "learn-surrealdb"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.204", features = ["derive"] }
surrealdb = { version = "1.5.4", features = ["kv-rocksdb"] }
tokio = { version = "1.38.0", features = ["full"] }
