[package]
name = "rust__minijinja"
version = "0.1.0"
edition = "2021"


[dependencies]
minijinja = "2.1.0"
chrono = { version = "0.4.38", features = ["serde"] }
serde = { version = "1.0.204", features = ["derive"] }
