- hosts: servers
  vars:
    - my_password: megapassword
  tasks:

    # Install passlib python package!!!
    - name: create a user a with plaintext password
      user:
        name: test_user
        password: "{{ my_password | password_hash('sha512') }}"
