- hosts: servers
  vars:
    # - ssh_key_path: /path/to/ssh_key.pub
  tasks:
    - name: Set only one ssh key
      copy: dest=/root/.ssh/authorized_keys content={{ lookup('file', ssh_key_path) }}

    - name: Enable root login over SSH
      lineinfile: dest=/etc/ssh/sshd_config regexp="^PermitRootLogin" line="PermitRootLogin yes" state=present
      notify:
        - restart sshd

    - name: Disable password login
      lineinfile: dest=/etc/ssh/sshd_config regexp="^PasswordAuthentication" line="PasswordAuthentication no" state=present
      notify:
        - restart sshd

  handlers:
    - name: restart sshd
      service: name=sshd state=restarted
