- hosts: servers
  tasks:
    - name: Add a repo key
      apt_key: url=https://repos.influxdata.com/influxdb.key

    - name: Add the repo
      apt_repository: repo="deb https://repos.influxdata.com/ubuntu {{ ansible_distribution_release | lower }} stable"

    - name: Install the apt package
      apt: pkg=telegraf
