[package]
name = "learn-sqlx"
version = "0.1.0"
edition = "2021"

[dependencies]
sqlx = { version = "0.8.0", features = [ "runtime-tokio", "postgres" ] }
tokio = { version = "1.38.1", features = ["full"] }
